### ISSUE TITLE
Initial commit & readme

### ISSUE THREAD

**Issue by alce65** [Liluminalia/202210-W3CH5-SARAFLORES-#5]
Hola Sara.
Está muy bien incluir en el readme las instrucciones del challenge, pero si dejas una imagen, asegúrate de que el enlace sea correcto, incluyendo la imagen en el commit inicial.
El readme es la presentación del proyecto y la tuya como developer.
Si está mal, no está invitando a seguir mirando nada dentro del proyecto.
Cámbialo cuando puedas y tenlo en cuenta en el futuro

**Comment by Liluminalia** [comment]
hola, llevas razon siempre se me olvida modificar la url, ya esta hecho :) lo tendre en cuenta en los siguientes, muchas gracias!

**Comment by alce65** [comment]
De nada. Muy bien, ya cierro el issue
