### ISSUE TITLE
Branch for the work in progress

### ISSUE THREAD

**Issue by alce65** [Liluminalia/202210-W3CH5-SARAFLORES-#7]
Hola Sara.
Veo que solo tienes la rama main en Github y supongo que ahora estarás trabajando en algo,
Recuerda que la rama con la feature en la que estemos trabajando se sube a remoto en cuanto tiene algún contenido. No hay que esperar a que este lista para la PR. De esta forma estamos salvaguardando nuestro trabajo en Github, por si acaso pasara algo en local.

**Comment by Liluminalia** [comment]
hola, pense que no habia que hacer PR hasta tenerlo terminado y asi borrar la rama, si te he entendido bien, ya esta subida, si me falta algo o no es asi dimelo por favor, muchas gracias!

**Comment by alce65** [comment]
Hola Sara.
En efecto la PR se puede hacer al terminar el trabajo, peor mientras se mantiene actualizada la rama remota con los cambios, por si en local hubiera algún problema.

**Comment by Liluminalia** [comment]
ah! antes complete la pull request, es simplemente hacer el push y dejar que quede ahi y ya cuando termine lo que este haciendo en la rama, si hago la PR el merge, y ya borro la rama, me he despistado, pero ya te entendi, lo tengo en cuenta, muchas gracias!

**Comment by alce65** [comment]
Genial. Lo importante es que lo hayas entendido.
Ya cierro la PR
